### ISSUE TITLE
GolangCI Swag

### ISSUE THREAD

**Issue by CodingFrieda** [golangci/golangci#1]
Do you have swag?

**Comment by golangci** [comment]
Hello!
What do you mean by swag?

**Comment by CodingFrieda** [comment]
For example t-shirts, mugs, stickers, plush and other stuff.
I can recommend @teezily ([homepage](https://www.teezily.com/de-de)), @qwertee ([homepage](https://www.qwertee.com/)), @opengoodies ([homepage](https://open-goodies.com/)), @stickermule ([homepage](https://www.stickermule.com/)) and @ZigPac ([homepage](https://wz-zigpac.en.alibaba.com/)).

**Comment by golangci** [comment]
We don't have a swag yet.
