### ISSUE TITLE
"Cannot activate repo" after changing GitHub username

### ISSUE THREAD

**Issue by elldritch** [golangci/golangci#14]
My guess is that you're storing GitHub authentication credentials against a GitHub username, when it needs to be stored against a GitHub user ID.

**Comment by jirfag** [comment]
hi!
thank you for reporting and suggesting the reason for the bug, and sorry for the bad experience.
You are right: we use username instead of ID.

**Comment by jirfag** [comment]
We started using ID instead of name for user and repo.
Also, I've deleted your second extra user. Log-out, log-in, and check, please.
