### ISSUE TITLE
No way to disconnect and reconnect repositories after manually deleting webhook

### ISSUE THREAD

**Issue by elldritch** [golangci/golangci#15]
I want to reconnect a repository to GolangCI after manually deleting the webhook, but the API returns 500. My guess is that it attempts to delete a non-existent GitHub webhook, gets an error from the GitHub API (since that webhook doesn't exist), and fails.

This makes it impossible for me to add the webhook back to my repository. In general, it would be great if a webhook URL was provided for authenticated repository owners to manually reconfigure their GitHub repository.

**Comment by elldritch** [comment]
I was able to work around this by manually retrieving the hook ID by inspecting the JS on the accounts page and manually adding a webhook to route `https://api.golangci.com/v1/repos/{owner}/{repo}/hooks/{hookID}` from https://github.com/golangci/golangci-api/blob/0a3d24e9b9b7c78f8cad42807b96aae48e4ca553/app/handlers/repos/hooks.go#L201.

Still, this webhook has a different hook ID in GitHub, so it's still impossible to disconnect the repository.

**Comment by jirfag** [comment]
hi!
Thank you for reporting and sorry for negative usage experience, we've fixed it, check, please
