### ISSUE TITLE
Visiting an unconnected repo's report URL causes internal server err

### ISSUE THREAD

**Issue by cpu** [golangci/golangci#17]
:wave: Hi folks,

Thanks for the awesome project! It's already been a helpful addition to the CI pipeline on a few of my projects. :beers: :bowing_man: 

I noticed that if I directly visit the "Report" link for a project I haven't connected to GolangCI the system produces a HTTP Status Code 500 Server Internal Error response.

I can reproduce this reliably visiting `https://golangci.com/r/github.com/letsencrypt/boulder`. It also appears to fail the same way if you visit a report URL for a Github user that exists but a repository that doesn't, e.g. `https://golangci.com/r/github.com/cpu/foobar`

**Comment by jirfag** [comment]
Hi!
thank you for reporting, we've made a message about connecting, you can check it for [letsencrypt/boulder](https://golangci.com/r/github.com/letsencrypt/boulder)

**Comment by cpu** [comment]
Perfect! Thanks @jirfag, I think that's sufficient to close this issue.
