### ISSUE TITLE
golangci is only reviewing the PRs of the person who added golangci

### ISSUE THREAD

**Issue by soupdiver** [golangci/golangci#19]
I'm working on a project with multiple developers. I have connected @golangci to our repos and when _I_ create a PR golangci is doing its review. But when someone else is opens a PR there is no review done.
Is that a permission issue or do I have to connect golangci in a special way to our repos?

**Comment by jirfag** [comment]
hi!
It should work for any user, I will check it

**Comment by jirfag** [comment]
I have found only two pull requests not from you after you have connected repos:
* [cloudradar-monitoring/cagent#14](https://github.com/cloudradar-monitoring/cagent/pull/14) - golangci checked it, it's ok
* [cloudradar-monitoring/cagent#15](https://github.com/cloudradar-monitoring/cagent/pull/15) - golangci checked it, it's ok

Could you give examples of not working pull requests?

Also I've fixed a bug with pull request reports for reconnected repos, now [report](https://golangci.com/r/github.com/cloudradar-monitoring/cagent/pulls/15) opens without errors

**Comment by soupdiver** [comment]
Sorry there was some misunderstanding and bad timing.
Seems the PR I was confused about was opened before golangci was fully connected.

My coworker opened a PR and things are fine. Thanks for checking anyway 👍

**Comment by jirfag** [comment]
good, thank you for reporting anyway!
