### ISSUE TITLE
Manually entering publicly available repository...

### ISSUE THREAD

**Issue by sean-** [golangci/golangci#2]
Is it possible to manually specify the public URL for a github repository?  The pagination doesn't appear to work.  Thanks in advance!

**Comment by golangci** [comment]
Thank you for issue! You are right: we don't have pagination yet :(
We've made a fast fix: increased count of repos we fetch from 90 to 1000.
Check it please.

**Comment by sean-** [comment]
Yup, that works!  I've tried connecting a few repos, sometimes it works successfully, sometimes it doesn't.  Regardless, thank you!

**Comment by golangci** [comment]
@sean- thank you!
You can't connect repo https://github.com/gwydirsam/go-scrum. GitHub API returns error, likely you're not owner of this repo and don't have rights to setup hooks. Our service can't work without hooks for pull request. We'are still investigating this issue and fixing errors handling to be more user-friendly.
