### ISSUE TITLE
GolangCI - Processing Timeout

### ISSUE THREAD

**Issue by zlav** [golangci/golangci#22]
GolangCI check's status is "Processing Timeout" and blocking a current PR. I am unable to retry or find any additional details about the timeout. It might be helpful to provide a link to the current details of the GolangCI status as well as a retry option to avoid situations where unexpected errors occur.

**Comment by jirfag** [comment]
sorry, now it should be fixed, check it please

**Comment by zlav** [comment]
All good, thank you!
