### ISSUE TITLE
Can't post connect the repo

### ISSUE THREAD

**Issue by xf0e** [golangci/golangci#36]
Hello i can't connect the repo "xf0e/open-ocr" because of error:

"Can't post activate repo request"

Can you help me?

Thanks!

**Comment by jirfag** [comment]
Hi!
Sorry for the slow response. I see that [it's connected](https://golangci.com/r/github.com/xf0e/open-ocr). How does it work now? Can you try to re-connect it, please?

**Comment by xf0e** [comment]
Hi, this is what is get if I try to connect the repo:
![image](https://user-images.githubusercontent.com/1162522/60996354-b887d200-a354-11e9-83bc-f910062798f6.png)

**Comment by jirfag** [comment]
Hi,
sorry for the slow response. I guess it was because of repo renaming, am I right? I've fixed it: now it works.
