### ISSUE TITLE
Go modules and GOPATH

### ISSUE THREAD

**Issue by keitwb** [golangci/golangci#37]
When I use the golangci.com service, it checks out my project in the GOPATH at `/go/src/...`.  I also vendor all dependencies in the project and thus use `-mod vendor` when making deps.  This causes everything related to modules to fail since modules don't work when running commands within the GOPATH.  The simple solution is to check out the project to somewhere outside of the GOPATH and everything would work fine.  I tried setting `project-path` to an absolute path but it still put things in the GOPATH.

Is there any way to check out the code outside of the GOPATH or do you know of some other workaround to make `-mod vendor` and modules work within the GOPATH?

**Comment by keitwb** [comment]
Example build: https://golangci.com/r/github.com/signalfx/signalfx-agent/pulls/712

**Comment by foxcpp** [comment]
If the GO111MODULE environment variable is set to on, modules are used even when building inside GOPATH.

See https://github.com/golang/go/wiki/Modules#how-to-install-and-activate-module-support

**Comment by jirfag** [comment]
Hi! sorry for the slow response. We are currently using go 1.13, therefor go modules are enabled by default
