### ISSUE TITLE
Error: failed to load program with go/packages

### ISSUE THREAD

**Issue by robdefeo** [golangci/golangci#38]
I am using go modules and getting the following error. 

```
$ GOLANGCI_COM_RUN=1 golangci-lint run --out-format=json --issues-exit-code=0 --deadline=5m --new=false --new-from-rev= --new-from-patch=
    Running error: context loading failed: failed to load program with go/packages: go [list -e -json -compiled -test=false -export=false -deps=true -find=false -- ./...]: exit status 2: # github.com/mailchain/mailchain/vendor/github.com/ethereum/go-ethereum/crypto/secp256k1
    vendor/github.com/ethereum/go-ethereum/crypto/secp256k1/curve.go:42:44: fatal error: libsecp256k1/include/secp256k1.h: No such file or directory
     #include "libsecp256k1/include/secp256k1.h"
                                                ^
    compilation terminated.
Error: failed to load program with go/packages
```

The prepare repo gets the repos but fails checking dependencies. 

```
    Synced deps
    Checking deps...
    internal/pkg/crypto/keys/secp256k1/private.go:1: vendor/github.com/ethereum/go-ethereum/crypto/secp256k1/curve.go:45:8: could not import C (no metadata for C) (typecheck)
    // Copyright 2019 Finobo
    internal/pkg/mailbox/pubkey.go:1: vendor/github.com/ethereum/go-ethereum/crypto/secp256k1/curve.go:45:8: could not import C (no metadata for C) (typecheck)
    // Copyright 2019 Finobo
    internal/pkg/clients/etherscan/api.go:1: vendor/github.com/ethereum/go-ethereum/crypto/secp256k1/curve.go:45:8: could not import C (no metadata for C) (typecheck)
    // Copyright 2019 Finobo
    Deps checking: bad: internal/pkg/crypto/keys/secp256k1/private.go:1: vendor/github.com/ethereum/go-ethereum/crypto/secp256k1/curve.go:45:8: could not import c (no metadata for c) (typecheck)
    Checking deps...
    internal/pkg/crypto/keys/secp256k1/private.go:1: vendor/github.com/ethereum/go-ethereum/crypto/secp256k1/curve.go:45:8: could not import C (no metadata for C) (typecheck)
    // Copyright 2019 Finobo
    internal/pkg/mailbox/pubkey.go:1: vendor/github.com/ethereum/go-ethereum/crypto/secp256k1/curve.go:45:8: could not import C (no metadata for C) (typecheck)
    // Copyright 2019 Finobo
    internal/pkg/clients/etherscan/api.go:1: vendor/github.com/ethereum/go-ethereum/crypto/secp256k1/curve.go:45:8: could not import C (no metadata for C) (typecheck)
    // Copyright 2019 Finobo
    Deps checking: bad: internal/pkg/crypto/keys/secp256k1/private.go:1: vendor/github.com/ethereum/go-ethereum/crypto/secp256k1/curve.go:45:8: could not import c (no metadata for c) (typecheck)
    [WARN] Failed to sync deps
    [WARN] Failed to fetch dependecies
```

Do you know how to resolve this?

**Comment by robdefeo** [comment]
More detail on the failed build: https://golangci.com/r/github.com/robdefeo/mailchain

**Comment by sb10** [comment]
Not sure if I have exactly the same problem, but I'm also getting this error message:

https://golangci.com/r/github.com/vertebrateresequencing/wr/pulls/209

> $ GOLANGCI_COM_RUN=1 golangci-lint run --out-format=json --issues-exit-code=0 --deadline=5m --new=false --new-from-rev= --new-from-patch=../changes.patch
    Running error: context loading failed: failed to load program with go/packages: go [list -e -json -compiled=true -test=true -export=false -deps=true -find=false -tags netgo -mod=readonly -- ./...]: exit status 1: build flag -mod=readonly only valid when using modules

However I don't seem to have had any problem with dependencies (except for some warnings due to an old version of go being used).

**Comment by jirfag** [comment]
hi!
@robdefeo you need to install C dependencies (to get `libsecp256k1/include/secp256k1.h`). You can use `prepare` section of [`.golangci.yml`](https://github.com/golangci/golangci/wiki/Configuration)

**Comment by robdefeo** [comment]
hi @jirfag thanks for your response. I spent a long time trying to figure this out. Do you have an example of what command I need to run?

**Comment by jirfag** [comment]
I've just tested it:
```bash
git clone https://github.com/mailchain/mailchain.git /tmp/mailchain
cd /tmp/mailchain
docker run --rm -v $(pwd):/goapp -e RUN=1 -e REPO=github.com/mailchain/mailchain golangci/build-runner goenvbuild
```
and it showed no errors - only found issues. This is the same mechanism golangci.com uses, and it's run with golangci-lint v1.21.0.

**Comment by robdefeo** [comment]
Thanks @jirfag I have this no working, very exciting to have this tool working on the first PR https://github.com/mailchain/mailchain/pull/328 :)

**Comment by Sggoodman** [comment]
Double check to see if the package is referenced circularly
