### ISSUE TITLE
Private repos and paid plans

### ISSUE THREAD

**Issue by golangci** [golangci/golangci#4]
Please thumb up the issue if you are interested in private github repos support as a paid monthly plan. We will notify you when it will be launched.

**Comment by nozzle** [comment]
@golangci do you have a timeline for offering support for private repos?

**Comment by jirfag** [comment]
hi @nozzle !
It's planned in 1-3 months

**Comment by nozzle** [comment]
Great! We're definitely planning on signing up for it :)

**Comment by ryanschneider** [comment]
Any updates on timing?

**Comment by jirfag** [comment]
the plan is the same: 2-6 weeks

**Comment by jirfag** [comment]
hi, thank you for waiting, we've launched private repos support! In gratitude for the waiting and support, I give you a coupon **github_private_repos_issue_coupon_20** with 20% discount. To use it just connect needed private repo - we will show organization settings and subscription form after that. Coupon can be activated till 10th February.

We don't have a trial version of subscription, so I recommend checking that your repo can be analyzed before subscribing: run

```bash
docker run --rm -v $(pwd):/goapp -e RUN=1 -e REPO=github.com/project/repo golangci/build-runner goenvbuild
```

like described in [doc](https://github.com/golangci/golangci/wiki/Configuration#how-to-test).

If it can't fetch private dependencies add `-e PRIVATE_ACCESS_TOKEN={TOKEN}`, where `{TOKEN}` is a GitHub token with access to private repos.

Feel free to report any regarding issues here or contact me via `denis@golangci.com`.
