### ISSUE TITLE
how to set golangci working directory

### ISSUE THREAD

**Issue by jinxiao** [golangci/golangci#44]
my source code is in a sub directory of my git repo which called src, so when i run `golangci-lint run --new-from-rev=HEAD~`  , would the option `--new-from-rev ` works well ?

 i think the option `--new-form-rev` may read the .git to tell which is the newest commits , but when i tried `golangci-lint run src/` it would showed like `cannot import absolute path ` , what should i do

**Comment by abustany** [comment]
This is I believe also affecting the hosted GolangCI service: I couldn't find how to tell it to cd to a subdirectory before running the analysis...

**Comment by symbiont-james-sedgwick** [comment]
+1
Not having access to parent directories of where the go code lives makes it impossible for us to set up some of our dependencies. We'd happily pay for hosted GolangCI if it were possible to run it on our repo (we use it just as a CircleCI job right now, where we can do whatever we want).

**Comment by jirfag** [comment]
Hi,
we've supported custom analysis paths. The option in `.golangci.yml` is `analyzed-paths`. See [documentation here](https://github.com/golangci/golangci/wiki/Configuration).

**Comment by byliuyang** [comment]
analyzed-paths is not working for project based on go module

**Comment by naturetime10** [comment]
@jirfag analyzed-paths is not working for project based on go module

**Comment by caldempsey** [comment]
@jirfag Also experiencing this, need a way to analyse applications of a monorepo (where one git repository has many sub-packages that make up their individual apps).

**Comment by symbiont-james-sedgwick** [comment]
@jirfag Same.
