### ISSUE TITLE
Organization repository is not shown

### ISSUE THREAD

**Issue by tpdenk** [golangci/golangci#45]
I cannot add an organization repo (public), or at least I don't find a way to do so.

The repo I would like to add is https://github.com/gojisvm/gojis, which was moved from https://github.com/TimSatke/gojis, where I've used golangci successfully.

I cannot use golangci by editing the webhook, by trying to enter the repo url in the search field manually, or by selecting the repo from the list of my repositories (because it doesn't show up).

Is there any kind of workaround?

**Comment by jirfag** [comment]
Hi,
sorry for the slow response.

You need to be a collaborator of the repo to be able to see it. And you need to be admin of the repo to be able to connect it. Can you become an admin in `https://github.com/gojisvm` organization?

**Comment by tpdenk** [comment]
I am the owner/admin/maintainer/everything. Is the issue resolved?

**Comment by jirfag** [comment]
you are right, sorry.
It's the first case when user is a colloborator in repository but GitHub API `https://api.github.com/user/repos` doesn't return it. I will dig into API docs and write to GitHub support.

**Comment by tsatke** [comment]
Any update? @jirfag 😄
