### ISSUE TITLE
golangci-lint 0.18 support

### ISSUE THREAD

**Issue by howardjohn** [golangci/golangci#46]
Seems currently golangci is not supporting the latest version. We rely on this change to support golang 1.13, so we were forced to upgrade but now we aren't getting the great PR feedback. Would be great for this to be supported as well.

Error messages are like `Failed to setup workspace: goenvbuild internal error: setup golangci-lint failed: no available minor version 18, see build log`

**Comment by yfei1** [comment]
+1 for 0.18 support ASAP.

**Comment by alexec** [comment]
This works for our build? Only bug appears to be the `--timeout` option.

**Comment by howardjohn** [comment]
Maybe support has been added since I filed this, we turned this off so I am not sure. If its fixed we can turn it back on

**Comment by yfei1** [comment]
I can confirm the support was added.

**Comment by jirfag** [comment]
sorry for the slow response, v1.21.1 is supported now
