### ISSUE TITLE
"Can't run golangci-lint: invalid output json, see build log", but no useful information in log

### ISSUE THREAD

**Issue by kortschak** [golangci/golangci#47]
At https://golangci.com/r/github.com/gonum/gonum/pulls/1129 we see "Can't run golangci-lint: invalid output json, see build log", but as the subject says, there is not useful information in the build log. The only JSON that is shown in the build log is indeed valid.

Something broken in the backend?

**Comment by AlekSi** [comment]
Same here with https://golangci.com/r/github.com/percona/pmm-managed/pulls/285.

**Comment by jirfag** [comment]
sorry, I gues I've forgotten to update one of the images. Now everything should work ok. And I've started recovering of already failed analyzes

**Comment by kortschak** [comment]
Thanks

**Comment by rekby** [comment]
I have the error now
https://golangci.com/r/github.com/rekby/lets-proxy2/pulls/101
