### ISSUE TITLE
GolangCI is calling older versions of golangci-lint with --timeout option

### ISSUE THREAD

**Issue by jannfis** [golangci/golangci#48]
Our integrations in GolangCI fail using latest Docker image with error message:

```bash
$ GOLANGCI_COM_RUN=1 golangci-lint run --out-format=json --issues-exit-code=0 --timeout=5m --new=false --new-from-rev= --new-from-patch=../changes.patch
    Can't get config for command line: can't parse args: unknown flag: --timeout
```

I suspect this is due to deprecation of `--deadline` switch in favour of `--timeout`, however the version we request via config (`1.18.0`) does not support `--timeout`.

**Comment by alexec** [comment]
@vthiery this error is caused by this commit https://github.com/golangci/golangci-worker/commit/060ed20e4b9f3a548fd45dec46a5f2c2b7313673#diff-95c251af319e7e1fd42f74f95f032e7c

**Comment by jirfag** [comment]
Sorry, I've fixed it. Now we use `--deadline` and golangci-lint v1.20.1 and 1.21.0 doesn't print deprecation error

**Comment by vthiery** [comment]
> @vthiery this error is caused by this commit [golangci/golangci-worker@060ed20#diff-95c251af319e7e1fd42f74f95f032e7c](https://github.com/golangci/golangci-worker/commit/060ed20e4b9f3a548fd45dec46a5f2c2b7313673#diff-95c251af319e7e1fd42f74f95f032e7c)

Ouch! Sorry for that :/
