### ISSUE TITLE
Not responding integration for over an hour

### ISSUE THREAD

**Issue by kwk** [golangci/golangci#5]
Hi. I have integrated the golangci into out repo and the PR check seems to be kicked off but is not responding for over an hour: https://github.com/fabric8-services/fabric8-wit/pull/1956

![bildschirmfoto von 2018-03-21 11-09-12](https://user-images.githubusercontent.com/193408/37704142-5caafd28-2cf8-11e8-8660-60bbdb4f3b66.png)

How long do we have to wait before there will be a report?

**Comment by golangci** [comment]
Hello!
Sorry for late response. There is an issue with `errcheck`: it eats more than 1GB on repo `fabric8-services/fabric8-wit`. Huge memory consumption breaks another linters and reporting.
We have partially fixed this issue by introducing analysis timeouts, after timeout (5 min) check status will be updated.

While we're still investigating memory consumption of `errcheck` we've disabled `errcheck` to prevent such issues.

Now everything should work fine on your repo.
