### ISSUE TITLE
--new not working

### ISSUE THREAD

**Issue by guettli** [golangci/golangci#55]
I added some code which should create new warnings.

Then I use the `--new` option, and hope to see only warnings which I introduced just now.

But there are no warnings at all.

I tried `--new-from-rev=HEAD~1`, too.

I have not commited my changes yet.

I guess that the current options look at the git history, and are not able to see my uncommited changes.

Is there a way to check my changes before I commit it?

**Comment by alexandear** [comment]
@guettli this repo is for [closed](https://medium.com/golangci/golangci-com-is-closing-d1fc1bd30e0e) GolangCI. Please create an issue that refers to the linter `golangci-lint` in https://github.com/golangci/golangci-lint

**Comment by guettli** [comment]
Thank you. I createat PR #56 so that this is more obvious.
