### ISSUE TITLE
GolangCI reports issues under my username and not as "golangci"

### ISSUE THREAD

**Issue by kwk** [golangci/golangci#6]
Hi,

We're happy that golangci works for our project now but it seems to be reporting in my name and not with its own name "golangci". Can I do something about this?

See this picture:

![bildschirmfoto von 2018-04-17 14-16-20](https://user-images.githubusercontent.com/193408/38869148-fcd9b558-4249-11e8-923c-490567849d63.png)

**Comment by golangci** [comment]
Hi @kwk!
Thank you for reporting issue, we've fixed it, check please.

**Comment by kwk** [comment]
Are these the fixes?

https://github.com/golangci/golangci-worker/commit/8fdd6cd8a6ef4933793ab5f6ddf249d9a525ff93
and 
https://github.com/golangci/golangci-worker/commit/2d9c45dded435b29c3f7f75b6cce6b23a78a5f61

It seems to me that you're not using golangci for building golangci, correct?

**Comment by golangci** [comment]
Yes, you are right. We don't use pull requests, but we will start from this day. And it's a fault to not use our service to check our code.
As you see this service is in an early stage and has some shortcomings and errors. We will be happy to hear any feedback from you.
