### ISSUE TITLE
no details link

### ISSUE THREAD

**Issue by adamdecaf** [golangci/golangci#8]
Usually CI tools I've seen offer a `Details` link that shows a log of the tool's execution. This is handy to help debug issues. 

Right now I'm not seeing anything to help debug #7 .

<img width="793" alt="screen shot 2018-05-28 at 11 58 01 am" src="https://user-images.githubusercontent.com/120951/40623810-7b2876f8-626e-11e8-81a6-7d232c7f3169.png">

**Comment by golangci** [comment]
Thank you for using and reporting, It's the cool idea and it's planned :)

**Comment by jirfag** [comment]
hi!
I implemented MVP for details link. Now it's enabled for success and failure statuses of pull request (no link when analysis in progress or an internal error occurred). Also, I am planning to add warnings, errors, and timings to the status page.

**Comment by golangci** [comment]
I have implemented timings and warnings in a report
