### ISSUE TITLE
golangci not catching junk in PR

### ISSUE THREAD

**Issue by JonKohler** [golangci/golangci#9]
Hey golangci team,
I'm working with the go-swagger team to enable golangci on their repo; however, after we turned it on and sent in a PR full of junk, golangCI says its A-OK :(

Is there a service level issue? or did we configure something wrong?

See the pile-o-junk PR here:
https://github.com/go-swagger/go-swagger/pull/1580

**Comment by jirfag** [comment]
Hi,
we already found the issue with your repo from our alerting service, we need some time to fix it. Also, currently we have no way to show errors of analysis to user. Fixing of that is planned for the near future

**Comment by JonKohler** [comment]
ok thank you!!

**Comment by JonKohler** [comment]
How are we looking on this fix?

**Comment by jirfag** [comment]
sorry for late response.

1. Analysis of your [go-swagger](https://github.com/go-swagger/go-swagger/pull/1580) works ok, you can see it in https://github.com/go-swagger/go-swagger/pull/1566: golangci left some comments about found issues there
2. There was a trouble analyzing junk in PR: golangci-lint didn't analyze the whole project if it found any critical parsing error. The critical error means corrupted `package` or `import` statement, like in this PR. I've fixed this behavior: now golangci-lint prints warning about it and continues analysis.
3. I restarted analysis of https://github.com/go-swagger/go-swagger/pull/1580, as you can see we commented on some issues, but not all: compilation errors isn't a common case and they prevent reporting of normal issues. I think we should make a test PR with real issues for govet, golint, gocyclo for every connected repo to demonstrate that it works. It's planned.
4. Now there is no way to see printed warnings (about some files with corrupted `package` or `import` statements) in GitHub or golangci.com. I am working on this issue.

**Comment by JonKohler** [comment]
ok @jirfag thanks! I'm glad I could break this in a fantastic fashion, as I think ultimately thats better for all consumers of the golangci service.

Thanks again!

**Comment by jirfag** [comment]
I agree, thank you!
